import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Krishna portfolio",
  description: "Generated by create next app for Krishna portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/letter-k-svgrepo-com.svg" type="image/x-icon" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
